-- Database Schema Export
-- Generated by extract_db_schema.py

-- Sequences
CREATE SEQUENCE admin_users_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE assessments_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE modules_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE questions_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE response_options_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE responses_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

CREATE SEQUENCE users_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    AS bigint;

-- Table: admin_users
CREATE TABLE admin_users (
    id integer DEFAULT nextval('admin_users_id_seq'::regclass) NOT NULL,
    username character varying NOT NULL,
    password_hash character varying NOT NULL,
    email character varying,
    role character varying,
    created_at timestamp without time zone,
    CONSTRAINT pk_admin_users PRIMARY KEY (id)
);

-- Table: assessments
CREATE TABLE assessments (
    id integer DEFAULT nextval('assessments_id_seq'::regclass) NOT NULL,
    user_id integer,
    total_score integer NOT NULL,
    max_possible_score integer NOT NULL,
    percentage numeric NOT NULL,
    classification character varying NOT NULL,
    completed_at timestamp without time zone,
    completion_time_seconds integer,
    CONSTRAINT pk_assessments PRIMARY KEY (id)
);

-- Table: modules
CREATE TABLE modules (
    id integer DEFAULT nextval('modules_id_seq'::regclass) NOT NULL,
    name character varying NOT NULL,
    description text,
    order_index integer NOT NULL,
    CONSTRAINT pk_modules PRIMARY KEY (id)
);

-- Table: questions
CREATE TABLE questions (
    id integer DEFAULT nextval('questions_id_seq'::regclass) NOT NULL,
    module_id integer,
    question_text text NOT NULL,
    question_type character varying,
    order_index integer NOT NULL,
    recommendations jsonb,
    CONSTRAINT pk_questions PRIMARY KEY (id)
);

-- Table: response_options
CREATE TABLE response_options (
    id integer DEFAULT nextval('response_options_id_seq'::regclass) NOT NULL,
    option_text character varying NOT NULL,
    points integer NOT NULL,
    excludes_from_calculation boolean,
    CONSTRAINT pk_response_options PRIMARY KEY (id)
);

-- Table: responses
CREATE TABLE responses (
    id integer DEFAULT nextval('responses_id_seq'::regclass) NOT NULL,
    user_id integer,
    question_id integer,
    response_option_id integer,
    open_response text,
    justification text,
    CONSTRAINT pk_responses PRIMARY KEY (id)
);

-- Table: users
CREATE TABLE users (
    id integer DEFAULT nextval('users_id_seq'::regclass) NOT NULL,
    name character varying NOT NULL,
    contact character varying,
    entity character varying,
    municipality character varying,
    created_at timestamp without time zone,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

